# This is a basic workflow to help you get started with Actions

name: Test CI Flutter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.4'
    - run: flutter pub get
    - run: flutter test
    - run: |
        mkdir $HOME/secrets
        gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SECRET_PASSPHRASE}}" \
        --output $HOME/secrets/secrets.tar secrets.tar.gpg
        tar xvf $HOME/secrets/secrets.tar
    - run: flutter build apk
    - run: flutter build appbundle
    # - run: flutter build ios --release --no-codesign
    - uses: actions/upload-artifact@v2
      with:
        name: Test apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: Deploy
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: alten
        releaseNotes: "A new version of the beloved app."
        file: build/app/outputs/apk/release/app-release.apk
